language: ruby
os: linux

install:
  - pip install --user sphinx

script:
  - make html

deploy:
  provider: pages
  repo: kevinstratford/test-sp
  target_branch: gh-pages
  local_dir: _build/html
  token: $TESTSP_TOKEN
  cleanup: false
  on:
    branch: master
