install:
  - pip install --user sphinx

script:
  - make html

deploy:
  provider: pages
  repo: kevinstratford/test-sp
  target-branch: gh-pages
  local-dir: _build/html
  github_token: $TESTSP_TOKEN
  skip-cleanup: true
  on:
    branch: master
